### ISSUE TITLE
NotImplementedError: lzc_get_props ??

### ISSUE THREAD

**Issue by ikus060** [ClusterHQ/pyzfs#33]
I wanned to try pyzfs to check if I could replace my "zfs" command line by pyzfs call.  I've install pyzfs using `pip2 install pyzfs` on a system with zfs on linux.

In a python prompt:
```
>>> libzfs_core.lzc_get_props('tank')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libzfs_core/_libzfs_core.py", line 721, in _f
    raise NotImplementedError(func.__name__)
NotImplementedError: lzc_get_props
```

Could I get more explanation about this exception ? Is it some compatibility issue with zfs onlinux ? I also tried `libzfs_core.lzc_create('tank/test2')` and it's working. Not sure where to go from here.

**Comment by yihuaf** [comment]
I don't think this repo is still maintained, unfortunately.

**Comment by avg-I** [comment]
Yes, indeed.
The code has been adopted by zfsonlinux project. All further development is happening there.
This project does not have any maintainers.
And, unfortunately, the README is not updated to point out those facts.

**Comment by yihuaf** [comment]
@avg-I Do you think it's a good idea to file an issue explaining this project is no longer maintained and points people to the new location? I think this is the best we can do given no one has write access to this repo any-more.

**Comment by ikus060** [comment]
That a shame. What is the project replacing this one in zfs on Linux?

**Comment by avg-I** [comment]
@yihuaf, I think that that is a good idea.

@ikus060, the code is here: https://github.com/zfsonlinux/zfs/tree/master/contrib/pyzfs
I am not sure if / how it is packaged.

**Comment by yihuaf** [comment]
#34 Filed
